name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IR_API_URL: "https://app.stage.invisirisk.com"

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        # uses: invisirisk/pse-action@feature/intermediate-deno-rust-ca-devtest
        uses: invisirisk/pse-action@develop
        
        with:
          api_url: ${{env.IR_API_URL}}
          app_token: ${{secrets.IR_API_KEY_STAGE}}
          # mode: docker-intercept
          # pse_image_tag: dev-test
          debug: true
      # ============= InvisiRisk Setup End =============
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # - name: Install dependencies
      #   run: npm install

      # - name: Build (host)
      #   run: npm run build
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     driver-opts: |
      #       network=host
      
      # - name: Docker build through PSE frontend
      #   run: BUILDKIT=1 docker build -t sample-npm-docker --build-arg BUILDKIT_SYNTAX=kkisalaya/pse-frontend:1.4.3 --secret id=pse-ca,src=/etc/ssl/certs/pse.pem  --build-arg PSE_PROXY=http://${PSE_PROXY_IP}:3128 --build-arg PSE_SKIP_OS_PKG_PROXY=false .
      # - name: Build Docker image simple
      #   run: BUILDKIT=1 docker build -t sample-npm-docker --build-arg BUILDKIT_SYNTAX=public.ecr.aws/w3c0c0n7/invisirisk/baf-buildkit:dev-test --secret id=pse-ca,src=/etc/ssl/certs/pse.pem  --build-arg PSE_PROXY=http://${PSE_PROXY_IP}:3128 .
  
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: sample-npm-docker
          build-args: |
            BUILDKIT_SYNTAX=public.ecr.aws/w3c0c0n7/invisirisk/baf-buildkit:latest
            PSE_PROXY=http://${{ env.PSE_PROXY_IP }}:3128
          secret-files: |
            pse-ca=/etc/ssl/certs/pse.pem

      # # ============= InvisiRisk Cleanup =============
      # - name: Cleanup PSE
      #   if: always()
      #   uses: invisirisk/pse-action@feature/intermediate-deno-rust-ca-devtest
      #   with:
          cleanup: "true"
          debug: true
      # # ============= InvisiRisk Cleanup End =============

