name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: 

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: ir-kkisalaya/pse-action@1.0
        with:
          app_token: ${{ secrets.IR_API_KEY }}
          mode: 'docker-intercept'
      # ============= InvisiRisk Setup End =============

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t sample-npm-docker \
            --build-arg BUILDKIT_SYNTAX=kkisalaya/pse-frontend:1.4.3 \
            --secret id=pse-ca,src=/etc/ssl/certs/pse.pem \
            --build-arg PSE_PROXY=http://${{ env.PSE_PROXY_IP }}:3128 \
            --build-arg PSE_SKIP_OS_PKG_PROXY=false .
        env:
          PSE_PROXY_IP: ${{ env.PSE_PROXY_IP }}

      - name: Run Docker container
        run: |
          docker run --rm \
            -e HTTP_PROXY=http://${{ env.PSE_PROXY_IP }}:3128 \
            -e HTTPS_PROXY=http://${{ env.PSE_PROXY_IP }}:3128 \
            -e NO_PROXY=localhost,127.0.0.1 \
            sample-npm-docker
        env:
          PSE_PROXY_IP: ${{ env.PSE_PROXY_IP }}

      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: ir-kkisalaya/pse-action@1.0
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
